version: '3'
services:
#   react:
#     build:
#       context: .
#       dockerfile: ./docker/react/Dockerfile
#     container_name: react_container
#     tty: true
#     volumes:
#       - ./react-app/react-app:/app/react
#     command: sh -c "cd /app/react && yarn install && yarn start"
#     ports:
#       - 3000:3000
  # go:
  #   build:
  #     context: .
  #     dockerfile: ./docker/golang/Dockerfile
  #   container_name: go_container
  #   ports:
  #     - 8000:8000
  #   tty: true
  #   volumes:
  #     - ./go-app:/app/go
  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web_events
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      # - ./sql/parch_and_posey.sql:/docker-entrypoint-initdb.d
    # links:
    #   - go